Microondas/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microondas.App.Models;

namespace Microondas.App.Controllers
{
    public class CadastroController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public JsonResult NovoPrograma(Programa programa)
        {
            Boolean sucess = false;
            if (ModelState.IsValid)
            {
                sucess = CriarArquivo.Arquivo(programa.nome, programa.tempo, programa.potencia, programa.caracter, programa.instrucao);
                if (sucess)
                {
                    ViewData["Message"] = "Cadastro realizado com sucesso!";

                }
            }
            return new JsonResult()
            {
                Data = new { result = sucess },
                JsonRequestBehavior = JsonRequestBehavior.DenyGet
            };
        }
    }
}

Microondas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Microondas Digital</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Novo", "Index", "Cadastro")</li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript" src="~/Scripts/controlador.js"></script>
    <script type="text/javascript" src="~/Scripts/cadastro.js"></script>

</body>
</html>